##The Service section defines a ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: wil42-app-service
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: wil42-app
---
##The Deployment section specifies the desired state of the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-app-deployment
  labels:
    app: wil42-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wil42-app
  template:
    metadata:
      labels:
        app: wil42-app
    spec:
      containers:
      - name: wil42-app-container
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  labels:
    app: wil42-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /wil42-app
        pathType: Prefix
        backend:
          service:
            name: wil42-app-service
            port:
              number: 8888
