## The Service section defines a ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: todo-app
---
## The Deployment section specifies the desired state of the application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: jesuisstan/todo-react-app:latest
        ports:
        - containerPort: 8888
---
## The Ingress section defines the Ingress resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
  labels:
    app: todo-app
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /todo-app
        pathType: Prefix
        backend:
          service:
            name: todo-app-service
            port:
              number: 8888
